import { MigrationInterface, QueryRunner } from "typeorm";

export class AddBuildingsAssetsIT1789475480272 implements MigrationInterface {
    name = 'AddBuildingsAssetsIT1789475480272'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" DROP CONSTRAINT "FK_fa24994e52be69851a9f224eb1d"`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" DROP CONSTRAINT "hire_equipment_production_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" DROP CONSTRAINT "hire_equipment_supplier_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hire_equipment_production"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hire_equipment_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hire_equipment_supplier"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hire_equipment_start_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vehicles_registration"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vehicles_mot_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vehicles_insurance_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vehicles_tax_date"`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" DROP CONSTRAINT "hire_equipment_status_check"`);
        await queryRunner.query(`CREATE TABLE "assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "category" character varying(100), "description" text, "purchase_date" date, "cost" numeric(10,2), "condition" character varying(100), "assigned_to" character varying(255), "maintenance_schedule" jsonb, "depreciation" jsonb, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_da96729a8b113377cfb6a62439c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "buildings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "address" text, "ownership_status" character varying(50), "lease_expiry" date, "landlord_contact" text, "access_code" text, "utilities" jsonb, "insurance_policies" jsonb, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bc65c1acce268c383e41a69003a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "it_resources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "type" character varying(50), "vendor" character varying(255), "subscription_start" date, "renewal_date" date, "cost" numeric(10,2), "credentials" text, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8ee88d979a2519a8b054df06dde" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "productions" DROP COLUMN "rollback_notice"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP COLUMN "bectu_rate"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP COLUMN "agreed_rate"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP COLUMN "line_margin_rate"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP COLUMN "is_above_line"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP COLUMN "set_id"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP COLUMN "line_type"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "qualifications"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "company_utr"`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" DROP COLUMN "effective_from"`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" DROP COLUMN "effective_to"`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" DROP COLUMN "rate_type"`);
        await queryRunner.query(`ALTER TABLE "materials_catalogue" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP COLUMN "rate_override"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP COLUMN "rank_override"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "supplier_code"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "street_name"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "zip_code"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "county"`);
        await queryRunner.query(`ALTER TABLE "production_documents" DROP COLUMN "file_size"`);
        await queryRunner.query(`ALTER TABLE "production_documents" DROP COLUMN "file_key"`);
        await queryRunner.query(`ALTER TABLE "production_documents" DROP COLUMN "file_mime_type"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" DROP COLUMN "mileage"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" DROP COLUMN "per_diem"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" DROP COLUMN "ad_hoc_reimbursement"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" DROP COLUMN "meal_allowance_breakfast"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" DROP COLUMN "meal_allowance_lunch"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" DROP COLUMN "meal_allowance_supper"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ALTER COLUMN "margin_rate" SET DEFAULT '0.1'`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" ALTER COLUMN "weekly_hire_rate" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" ADD CONSTRAINT "FK_22fe15e9f71b1bd7174b489f5b7" FOREIGN KEY ("materials_catalogue_id") REFERENCES "materials_catalogue"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" ADD CONSTRAINT "FK_b3718785d431c85f315ebd1c15b" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" ADD CONSTRAINT "FK_29645f2150e533d231a51696c15" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "hire_equipment" DROP CONSTRAINT "FK_29645f2150e533d231a51696c15"`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" DROP CONSTRAINT "FK_b3718785d431c85f315ebd1c15b"`);
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" DROP CONSTRAINT "FK_22fe15e9f71b1bd7174b489f5b7"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" ALTER COLUMN "weekly_hire_rate" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ALTER COLUMN "margin_rate" SET DEFAULT 0.1`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ADD "meal_allowance_supper" numeric`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ADD "meal_allowance_lunch" numeric`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ADD "meal_allowance_breakfast" numeric`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ADD "ad_hoc_reimbursement" numeric DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ADD "per_diem" numeric DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ADD "mileage" numeric DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "production_documents" ADD "file_mime_type" text`);
        await queryRunner.query(`ALTER TABLE "production_documents" ADD "file_key" text`);
        await queryRunner.query(`ALTER TABLE "production_documents" ADD "file_size" bigint`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "county" text`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "city" text`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "zip_code" text`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "street_name" text`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "supplier_code" text`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD "rank_override" text`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD "rate_override" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "materials_catalogue" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" ADD "rate_type" text DEFAULT 'bectu'`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" ADD "effective_to" date`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" ADD "effective_from" date`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "company_utr" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "qualifications" text array DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD "line_type" text`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD "set_id" uuid`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD "is_above_line" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD "line_margin_rate" numeric(5,4) DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD "agreed_rate" numeric(10,2) DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD "bectu_rate" numeric(10,2) DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "productions" ADD "rollback_notice" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar_url" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`DROP TABLE "it_resources"`);
        await queryRunner.query(`DROP TABLE "buildings"`);
        await queryRunner.query(`DROP TABLE "assets"`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" ADD CONSTRAINT "hire_equipment_status_check" CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'returned'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "idx_vehicles_tax_date" ON "vehicles" USING btree ("tax_renewal_date") `);
        await queryRunner.query(`CREATE INDEX "idx_vehicles_insurance_date" ON "vehicles" USING btree ("insurance_renewal_date") `);
        await queryRunner.query(`CREATE INDEX "idx_vehicles_mot_date" ON "vehicles" USING btree ("mot_expiry_date") `);
        await queryRunner.query(`CREATE INDEX "idx_vehicles_registration" ON "vehicles" USING btree ("registration_number") `);
        await queryRunner.query(`CREATE INDEX "idx_hire_equipment_start_date" ON "hire_equipment" USING btree ("hire_start_date") `);
        await queryRunner.query(`CREATE INDEX "idx_hire_equipment_supplier" ON "hire_equipment" USING btree ("supplier_name") `);
        await queryRunner.query(`CREATE INDEX "idx_hire_equipment_status" ON "hire_equipment" USING btree ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_hire_equipment_production" ON "hire_equipment" USING btree ("production_id") `);
        await queryRunner.query(`ALTER TABLE "hire_equipment" ADD CONSTRAINT "hire_equipment_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hire_equipment" ADD CONSTRAINT "hire_equipment_production_id_fkey" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" ADD CONSTRAINT "FK_fa24994e52be69851a9f224eb1d" FOREIGN KEY ("materials_catalogue_id") REFERENCES "materials_catalogue"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
